# Generated by Django 4.2.4 on 2024-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0012_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(max_length=250, upload_to='studentapp/static/assets/profile/'),
        ),
    ]
